---
name: "SortingAdditions"
guid: "144e0b9a-c908-416c-a11f-b495b6c52093"
version: "1.0.0.8"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Adds extra sorting options to the library."
description: >
  This plugin adds extra sorting options to the library, such as sorting by date added, release date, or custom metadata fields. It also allows users to create custom sorting rules based on their preferences.
category: "General"
owner: "AnzoDK"
artifacts:
- "Jellyfin.Plugin.SortAdditions.dll"
changelog: >
  changelog
